version: "3"
services:
  mongo:
    container_name: orm-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/mysql
    ports:
      - 27017:27017
volumes:
  mongo_data:
    name: global_mongo
